config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='')),
    path('accounts/', include('account.urls', namespace='')),
    path('projects/', include('project.urls', namespace='')),
]

# Необходимо для работы debug_toolbar
if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls)), ] + urlpatterns

core/urls.py
from django.urls import path

from core.views import IndexView

app_name = 'core'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

project/urls.py
from django.urls import path

from project.views import (
    add_keyword_group,
    get_keywords_and_keyword_groups_of_project,
    get_filtered_project_data,
    get_project_search_engines,
    get_regions,
    remove_keyword_or_group_of_keywords,
    remove_search_system,
    search_project_in_user_projects,
    start_checking_keyword_groups,
    KeywordsAddingView,
    AddProjectView,
    KeywordEditingView,
    ProjectEditView,
    DetailProjectView,
    SearchSystemsAddingView,
    SearchSystemsEditingView,
)

app_name = 'project'
urlpatterns = [
    path('ajax/get_keywords_and_keyword_groups_of_project/', get_keywords_and_keyword_groups_of_project,
         name='get_keywords_and_keyword_groups_of_project'),
    path('ajax/get_project_search_engines/', get_project_search_engines,
         name='get_project_search_engines'),
    path('ajax/<slug:slug>/add_keywords_group/', add_keyword_group, name='add_group_of_keywords'),
    path('ajax/filter_project_data/', get_filtered_project_data, name='filter_project_data'),
    path('ajax/regions/', get_regions, name='get_regions'),
    path('ajax/remove_keyword_or_group_of_keywords/', remove_keyword_or_group_of_keywords,
         name='remove_keyword_or_group_of_keywords'),
    path('ajax/remove_search_system/', remove_search_system, name='remove_search_system'),
    path('ajax/start_checking_keyword_groups/', start_checking_keyword_groups,
         name='start_checking_keyword_groups'),
    path('ajax/search_project_in_user_projects/', search_project_in_user_projects,
         name='search_project_in_user_projects'),
    path('<slug:slug>/keywords/add/', KeywordsAddingView.as_view(), name='add_keywords'),
    path('<slug:slug>/search_system/add/', SearchSystemsAddingView.as_view(), name='add_search_system'),
    path('add/', AddProjectView.as_view(), name='project_create'),
    path('<slug:slug>/settings/keywords/edit/', KeywordEditingView.as_view(), name='edit_keywords'),
    path('<slug:slug>/settings/project/edit/', ProjectEditView.as_view(), name='edit_project'),
    path('<slug:slug>/settings/search_systems/edit/', SearchSystemsEditingView.as_view(), name='edit_search_systems'),
    path('<slug:slug>/', DetailProjectView.as_view(), name='project_details'),

]

project/models.py
from dateutil.relativedelta import relativedelta
from django.db import models
from django.urls import reverse
from django.utils.dateformat import DateFormat
from django.utils.text import slugify
from pydantic import BaseModel, validator, HttpUrl
from urllib.parse import urlparse

from account.models import CustomUser


def get_slug(url: str):
    parsed_url = urlparse(url)
    modified_domain = parsed_url.netloc.replace('.', '_')
    return slugify(modified_domain)


class Keywords(models.Model):
    name = models.TextField('Перечень слов', max_length=10000)
    keyword_groups = models.ForeignKey(
        'KeywordGroups',
        verbose_name='Группа ключевых слов',
        on_delete=models.CASCADE
    )

    class Meta:
        ordering = ('id',)
        verbose_name = 'Слово'
        verbose_name_plural = 'Слова'

    def __str__(self):
        return self.name

    def as_json(self, *args):
        return {field_name: getattr(self, field_name) for field_name in args}


class KeywordGroups(models.Model):
    name = models.CharField('Название группы', max_length=255)

    project = models.ForeignKey(
        'Project',
        verbose_name='Проект',
        on_delete=models.CASCADE
    )

    search_systems = models.ManyToManyField(
        'SearchSystem',
        blank=True
    )

    class Meta:
        ordering = ('id',)
        verbose_name = 'Группа ключевых слов'
        verbose_name_plural = 'Группы ключевых слов'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('project:keywords_group_detail', kwargs={'pk': self.id})

    def as_json(self, *args):
        keyword_groups_data = {}

        for field_name in args:
            if field_name == 'keywords':
                keywords_set = self.keywords_set.all()
                if keywords_set:
                    list_keywords = [keyword.as_json('id', 'name') for keyword in keywords_set]
                    keyword_groups_data['keywords'] = list_keywords
            else:
                keyword_groups_data[field_name] = getattr(self, field_name)

        return keyword_groups_data

    def keyword_group_search_system(self):
        return [search_system for search_system in self.search_systems.all()]

    keyword_group_search_system.short_description = 'Поисковые системы группы ключевых слов'


class PositionRequestPydantic(BaseModel):
    project_id: int
    domain: HttpUrl
    search_system_id: int
    keyword_group_id: int
    region_id: int
    query_keywords: str
    position: int = None
    url_site: HttpUrl = None


class Project(models.Model):
    LIMIT_HUNDRED = 100
    LIMIT_TWO_HUNDRED = 200

    LIMIT_CHOICES = (
        (LIMIT_HUNDRED, '100'),
        (LIMIT_TWO_HUNDRED, '200'),
    )

    DATE_CHOICES = (
        ('daily', 'Ежедневно'),
        ('every_three_days', 'Раз в 3 дня'),
        ('weekly', 'Раз в неделю'),
        ('monthly', 'Раз в месяц'),
        ('on_request', 'По запросу'),
    )

    name = models.CharField('Название проекта', max_length=255)
    slug = models.SlugField('Символьный код проекта', max_length=50, unique=True, db_index=True)
    domain = models.URLField(
        'Адрес сайта',
        max_length=50,
        unique=True,
        error_messages={
            'unique': 'Проект с таким адресом уже существует'
        }
    )

    limit_position = models.IntegerField(
        'Глубина сбора позиций',
        choices=LIMIT_CHOICES,
        default=LIMIT_HUNDRED,
        help_text='Сервис будет искать сайт включительно до 100-й или 200-й позиции'
    )

    start_check = models.CharField(
        'Периодичность проверок',
        max_length=30,
        choices=DATE_CHOICES,
        default='weekly',
    )

    created = models.DateTimeField('Дата добавления', auto_now_add=True)

    updated = models.DateTimeField('Дата изменения', auto_now=True)

    date_of_check = models.DateTimeField('Дата проверки', blank=True, null=True)

    date_of_next_check = models.DateTimeField('Дата следующей проверки', blank=True, null=True)

    author = models.ForeignKey(
        CustomUser,
        verbose_name='Автор проекта',
        on_delete=models.CASCADE
    )

    class Meta:
        ordering = ('-id',)
        verbose_name = 'Проект'
        verbose_name_plural = 'Проекты'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        # if not self.id:
        self.slug = get_slug(self.domain)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('project:project_details', kwargs={'slug': self.slug})

    def get_next_check_date(self, date_of_check):
        if self.start_check == 'daily':
            return date_of_check + relativedelta(days=1)

        elif self.start_check == 'every_three_days':
            return date_of_check + relativedelta(days=3)

        elif self.start_check == 'weekly':
            return date_of_check + relativedelta(weeks=1)

        elif self.start_check == 'monthly':
            return date_of_check + relativedelta(months=1)


class RankingsSite(models.Model):
    position = models.PositiveSmallIntegerField('Позиция сайта', )
    position_difference = models.SmallIntegerField('Разница позиций', null=True)
    project = models.ForeignKey(
        Project,
        verbose_name='Проект',
        on_delete=models.CASCADE
    )
    url_site = models.URLField('Адрес сайта', max_length=255)

    keywords = models.CharField('Ключевые слова', max_length=150)

    keyword_groups = models.ForeignKey(
        KeywordGroups,
        verbose_name='Группы ключевых слов',
        on_delete=models.CASCADE,
    )
    created = models.DateTimeField('Дата добавления', auto_now_add=True)
    updated = models.DateField('Дата изменения', auto_now=True)
    search_system = models.ForeignKey(
        'SearchSystem',
        verbose_name='Поисковая система',
        on_delete=models.CASCADE,
    )

    class Meta:
        ordering = ('-id',)
        verbose_name = 'Позиция сайта'
        verbose_name_plural = 'Позиции сайта'

    def as_json(self, *args):
        site_ranking = {}

        for field_name in args:
            if field_name == 'date_of_check':
                date_format = DateFormat(self.created)
                site_ranking['date_of_check'] = date_format.format('d.m.y')
            elif field_name == 'url_site':
                url_site = getattr(self, field_name)
                url_parsed = urlparse(url_site)
                site_ranking['url_site'] = url_parsed.path
            elif field_name == 'search_system':
                search_system = self.search_system.as_json('name', 'city')
                site_ranking['search_system'] = f'{search_system["name"]}, {search_system["city"]}'
            elif field_name == 'keyword_group':
                site_ranking['keyword_group'] = self.keyword_groups.as_json('name')
            elif field_name == 'keyword_groups':
                search_system_keyword_groups = self.search_system.keywordgroups_set.all()
                site_ranking['keyword_groups'] = [keyword_group.as_json('id', 'name') for keyword_group in
                                                  search_system_keyword_groups]
            else:
                site_ranking[field_name] = getattr(self, field_name)

        return site_ranking


class SearchEnginePydantic(BaseModel):
    name: str
    country: str
    city: str
    city_id: int
    language: str

    @validator('country', 'city')
    def field_value_is_a_string(cls, name):
        if name.isdigit():
            raise ValueError('Значение не должно быть только числом.')
        return name


class SearchSystem(models.Model):
    YANDEX = 'yandex'
    GOOGLE = 'google'
    ENGLISH = 'en'
    RUSSIAN = 'ru'

    LANGUAGE_CHOICES = (
        (ENGLISH, 'english'),
        (RUSSIAN, 'русский'),
    )

    SEARCH_SYSTEM_CHOICES = (
        (YANDEX, 'яндекс'),
        (GOOGLE, 'google'),
    )

    name = models.CharField(
        'Поисковая система',
        max_length=25,
        choices=SEARCH_SYSTEM_CHOICES,
        default=YANDEX
    )

    country = models.CharField('Страна', max_length=50)

    city = models.CharField('Регион', max_length=100)

    geo_id_city = models.IntegerField('Geo id города', )

    language = models.CharField(
        'Язык',
        max_length=25,
        choices=LANGUAGE_CHOICES,
        default=RUSSIAN
    )

    project = models.ForeignKey(
        Project,
        verbose_name='Проект',
        on_delete=models.CASCADE
    )

    class Meta:
        ordering = ('id',)
        verbose_name = 'Поисковая система'
        verbose_name_plural = 'Поисковые системы'

    def __str__(self):
        return f'{self.name}, {self.city}'

    def get_absolute_url(self):
        return reverse('project:search_system_detail', kwargs={'pk': self.pk})

    def as_json(self, *args):
        return {field_name: getattr(self, field_name) for field_name in args}

project/forms.py
from django import forms

from project.models import (
    Keywords,
    KeywordGroups,
    Project,
    SearchSystem
)


class FormAddingKeywordGroups(forms.ModelForm):
    name = forms.CharField(
        label='Название группы',
        max_length=255
    )

    class Meta:
        model = KeywordGroups
        fields = ('name',)


class KeywordsAddingForm(forms.ModelForm):
    name = forms.Textarea()

    class Meta:
        model = Keywords
        fields = ('name', 'keyword_groups')

    def __init__(self, *args, **kwargs):
        super(KeywordsAddingForm, self).__init__(*args, **kwargs)
        initial = kwargs.get('initial')
        self.fields['keyword_groups'].queryset = KeywordGroups.objects.filter(project__slug=initial['slug'])


class ProjectAddingForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ('name', 'domain', 'limit_position', 'start_check')


class ProjectEditingForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ('name', 'domain', 'limit_position', 'start_check')


class SearchSystemsAddingForm(forms.ModelForm):
    class Meta:
        model = SearchSystem
        fields = ('name', 'country', 'city', 'language')

templates/partials/add_keywords.html
{% load bootstrap5 %}

<div class="container-fluid">

    <div class="d-flex flex-column align-items-center my-5">

        <div class="col-md-8 col-sm-12">
            <h3 class="text-center mb-3 p-2">Ключевые слова</h3>
            <p class="my-1 p-1">
                Отслеживайте позиции сайта по всем интересующим вас ключевым словам.
                Для получения полной картины дополните семантику своего сайта ключевыми словами, собранными при
                помощи сервиса.
            </p>
        </div>

        <form method="post" id="form_id_for_add_keywords"
              action="{% url 'project:add_keywords' view.kwargs.slug %}"
              class="col-md-8 col-sm-12 mt-5">

            {% csrf_token %}

            <div class="mb-3 row">
                <label class="col-md-3 col-form-label" for="id_name">Добавить слова</label>
                <div class="col-md-9">
                        <textarea name="keywords" cols="40" rows="10" maxlength="10000"
                                  class="form-control" placeholder="Перечень слов" title=""
                                  required="required" id="id_keywords"></textarea>
                </div>
            </div>

            <div class="mb-3 row">
                <label class="col-md-3 col-form-label" for="id_keyword_groups">Группа ключевых слов</label>
                <div class="col-md-9">
                    <select name="keyword_groups" class="form-select" title=""
                            required="required" id="id_keyword_groups"
                            data-url="{% url 'project:add_group_of_keywords' view.kwargs.slug %}">
                        <option value="" selected="">---------</option>
                        {% for one_group_of_keywords in keyword_groups %}
                            <option value="{{ one_group_of_keywords.id }}">{{ one_group_of_keywords }}</option>
                        {% endfor %}
                        <option value="-1" id="createGroup">Создать группу</option>
                    </select>
                </div>
            </div>

            <input type="hidden" name="next" value="{{ next }}">

            <div class="mt-5">
                <button class="btn btn-outline-success" type="submit">Добавить ключевые слова</button>
            </div>

        </form>


        <div class="col-md-5 col-sm-12 mt-3"
             data-url="{% url 'project:add_group_of_keywords' view.kwargs.slug %}"
             id="id_create_keyword_group">
        </div>


        <div class="col-md-8 col-sm-12 mt-5">

            <div class="d-flex justify-content-between">
                <a class="btn btn-outline-primary" type="button"
                   href="{% url 'project:edit_project' view.kwargs.slug %}">Назад</a>
                <a class="btn btn-outline-primary" href="{% url 'project:add_search_system' view.kwargs.slug %}"
                   type="button">Далее</a>
            </div>

        </div>

    </div>

    <div class="d-flex flex-column  align-items-center mt-3" id="listOfKeywordGroupsWithKeywords"
         data-project-slug="{{ view.kwargs.slug }}"
         data-url="{% url 'project:get_keywords_and_keyword_groups_of_project' %}">

        <h4 class="text-center mb-3 p-2">Ключевые слова проекта:</h4>

        <ul class="col-md-8 col-sm-12" id="keyword_groups_list_id"
            data-url="{% url 'project:remove_keyword_or_group_of_keywords' %}">

            {% for keyword_group in keyword_groups %}

                <li class="d-flex justify-content-between">
                    <div class="my-1 p-1">{{ keyword_group }} :</div>
                    <div>
                        <a class="btn btn-outline-danger btn-sm js-remove-keyword-group" type="button"
                           data-keyword-group-id="{{ keyword_group.id }}">Удалить</a>
                    </div>
                </li>

                <ul id="keywordGroupID{{ keyword_group.id }}">
                    {% for keyword in keyword_group.keywords_set.all %}

                        <li class="d-flex justify-content-between my-2">
                            <div class="my-1 p-1">{{ keyword }}</div>
                            <div>
                                <a class="btn btn-outline-danger btn-sm js-remove-keyword" type="button"
                                   data-keyword-id="{{ keyword.id }}">Удалить</a>
                            </div>
                        </li>

                    {% endfor %}
                </ul>

            {% endfor %}

        </ul>

    </div>

</div>

templates/partials/add_search_system.html
{% load bootstrap5 %}

<div class="container-fluid">

    <div class="d-flex flex-column align-items-center my-3">

        <div class="col-md-8 col-sm-12">
            <h3 class="text-center mb-3 p-2">Поисковые системы</h3>
            <p class="my-1 p-1">
                Отслеживайте позиции по интересующим вас ключевым словам в Яндекс в любых регионах мира.
            </p>
        </div>

        <form method="post" class="col-md-8 col-sm-12 mt-5" id="id_form_search_system"
              action="{% url 'project:add_search_system' view.kwargs.slug %}">

            {% csrf_token %}

            <div class="mb-3 row">
                <label class="col-md-3 col-form-label" for="id_name">Поисковая система</label>
                <div class="col-md-9">
                    <select name="name" class="form-select" title="" id="id_name">
                        <option value="yandex" selected="">Яндекс</option>
                        <option value="google">Google</option>
                    </select>
                </div>
            </div>

            <div class="mb-3 row">
                <label class="col-md-3 col-form-label" for="id_country">Страна</label>
                <div class="col-md-9">
                    <input type="text" name="country" maxlength="50"
                           class="form-control" placeholder="Страна" title="" required="required"
                           id="id_country">
                </div>
            </div>

            <div class="mb-3 row">
                <label class="col-md-3 col-form-label" for="id_select_city">Регион</label>
                <div class="col-md-9">
                    <input type="text" name="city" maxlength="100" class="form-control"
                           placeholder="Регион" title="" required="required"
                           id="id_select_city" data-url="{% url 'project:get_regions' %}">

                </div>
            </div>

            <div class="mb-3 row">
                <label class="col-md-3 col-form-label" for="id_language">Язык</label>
                <div class="col-md-9">
                    <select name="language" class="form-select" title="" id="id_language">
                        <option value="en">English</option>
                        <option value="ru" selected="">Русский</option>
                    </select>
                </div>
            </div>

            <input type="hidden" name="next" value="{{ next }}">

            <input type="hidden" name="city_id">

            <div class="mt-5">
                <button class="btn btn-outline-success" type="submit">Добавить поисковую систему</button>
            </div>

        </form>

        <div class="col-md-8 col-sm-12 mt-5">

            <div class="d-flex justify-content-between">
                <a class="btn btn-outline-primary" type="button"
                   href="{% url 'project:add_keywords' view.kwargs.slug %}">Назад</a>
                <a class="btn btn-outline-primary" href="{% url 'core:index' %}" type="button">Далее</a>
            </div>

        </div>

    </div>


    <div class="d-flex flex-column  align-items-center" data-project-slug="{{ view.kwargs.slug }}"
         id="search_systems">

        <h4 class="text-center mt-3 p-2">Поисковые системы добавленные к этому проекту</h4>

        <div class="col-md-8 col-sm-12 mt-1" id="search_systems_list_id"
             data-url="{% url 'project:get_project_search_engines' %}"
             data-object-delete-url="{% url 'project:remove_search_system' %}">

            <ol>
                {% for search_system in search_systems %}
                    <li class="d-flex justify-content-between my-2">
                        <div class="my-1 p-1">{{ search_system }}</div>
                        <div>
                            <a class="btn btn-outline-danger btn-sm js-remove-search-system"
                               type="button" data-search-system-id="{{ search_system.id }}">Удалить</a>
                        </div>
                    </li>

                {% endfor %}
            </ol>
        </div>

    </div>

</div>

templates/partials/pagination.html
{% load bootstrap5 %}

{# Просто вставить данный шаблон в то место где нужна пагинация #}
{#        {% include 'partials/pagination.html' %}      #}

{% if is_paginated %}

    <nav aria-label="Page navigation example ">
        <ul class="pagination justify-content-end pagination-sm mx-3 p-1">

            <li class="page-item {% if not prev_page_url %} disabled {% endif %}">
                <a class="page-link" href="{{ prev_page_url }}" tabindex="-1" aria-disabled="true">Предыдущая</a>
            </li>

            {% for page_number in site_ratings.paginator.page_range %}

                {% if site_ratings.number == page_number %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                    </li>
                {% elif page_number > site_ratings.number|add:-3 and page_number < site_ratings.number|add:3 %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                    </li>
                {% endif %}

            {% endfor %}

            <li class="page-item {% if not next_page_url %} disabled {% endif %}">
                <a class="page-link" href="{{ next_page_url }}" tabindex="-1" aria-disabled="true">Следующая</a>
            </li>

        </ul>
    </nav>

{% endif %}

templates/partials/sidebar.html
<div class="d-flex flex-column flex-shrink-0 p-3">

    <form class="align-self-stretch mt-4"
          action="{% url 'project:search_project_in_user_projects' %}"
          id="sidebar_form_id">
        {% csrf_token %}
        <div>
            <input class="form-control" type="search" name="search_for_projects"
                   id="searching_projects" placeholder="Поиск проектов ..." maxlength="25">
        </div>
    </form>

    <h5 class="align-self-start mt-4 mb-2 px-3">Проекты</h5>

    <ul class="nav nav-pills flex-column" id="sidebar-id" style="font-size: 17px; padding-inline-start: 0;">
        {% for project in all_user_projects %}
            <li class="d-flex flex-row justify-content-between align-items-center">

                <div>
                    <a class="nav-link" href="{{ project.get_absolute_url }}"
                       style="color: #EEEEEE; text-decoration:none;">{{ project.name }}</a>
                </div>

                <div class="d-flex flex-row justify-content-between">
                    <div>
                        <a class="btn btn-light btn-sm me-2" href="#" type="button"
                           style="background-color: #E9F2FD; color: #454545; width: 55px">
                            {% if project.date_of_check %}
                                {{ project.date_of_check|date:"d.m" }}
                            {% else %}
                                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor"
                                     class="bi bi-exclamation-triangle" viewBox="0 0 16 16">
                                    <path d="M7.938 2.016A.13.13 0 0 1 8.002 2a.13.13 0 0 1 .063.016.146.146 0 0 1 .054.057l6.857 11.667c.036.06.035.124.002.183a.163.163 0 0 1-.054.06.116.116 0 0 1-.066.017H1.146a.115.115 0 0 1-.066-.017.163.163 0 0 1-.054-.06.176.176 0 0 1 .002-.183L7.884 2.073a.147.147 0 0 1 .054-.057zm1.044-.45a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566z"/>
                                    <path d="M7.002 12a1 1 0 1 1 2 0 1 1 0 0 1-2 0zM7.1 5.995a.905.905 0 1 1 1.8 0l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995z"/>
                                </svg>
                            {% endif %}
                        </a>
                    </div>
                    <div>
                        <a class="btn btn-light btn-sm" href="{% url 'project:edit_project' project.slug %}"
                           type="button" style="background-color: #E9F2FD; color: #454545; width: 55px">edit
                        </a>
                    </div>
                </div>

            </li>
        {% empty %}
            <li class="mt-1 p-1">У вас нет проектов.</li>
        {% endfor %}
    </ul>

    <div class="align-self-center mt-4" id="start_checking_projects">
        <a class="btn btn-primary js-get-positions" data-project-slug="{{ project.slug }}"
           data-url="{% url 'project:start_checking_keyword_groups' %}"
           data-running_check_status="checking_all_user_projects"
           type="button" id="id_of_button_to_start_checking">Снять все позиции</a>
    </div>

</div>

templates/partials/sidebar_with_settings.html
<div class="d-flex flex-column align-items-start px-2 py-2 mx-3 mt-5 ">

    <h3 class="align-self-center p-2 mb-3">{{ project.name }}</h3>

    <div class="my-1 p-1">
        <a class="btn btn-link" href="{% url 'project:edit_project' project.slug %}" type="button"
           style="color: #EEEEEE;">Общая информация</a>
    </div>
    <div class="my-1 p-1">
        <a class="btn btn-link" href="{% url 'project:edit_keywords' project.slug %}" type="button"
           style="color: #EEEEEE;">Ключевые слова</a>
    </div>
    <div class="my-1 p-1">
        <a class="btn btn-link" href="{% url 'project:edit_search_systems' project.slug %}" type="button"
           style="color: #EEEEEE;">Поисковые системы</a>
    </div>

</div>