account/urls.py
from django.urls import path

from account.views import (
    AccountLoginView,
    AccountLogoutView,
    RegisterAccountView,
)

app_name = 'account'
urlpatterns = [
    path('register/', RegisterAccountView.as_view(), name='register'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='')),
    path('accounts/', include('account.urls', namespace='')),
    path('projects/', include('project.urls', namespace='')),
]

# Необходимо для работы debug_toolbar
if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls)), ] + urlpatterns

core/urls.py
from django.urls import path

from core.views import IndexView

app_name = 'core'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

project/urls.py
from django.urls import path

from project.views import (
    add_keyword_group,
    get_keywords_and_keyword_groups_of_project,
    get_filtered_project_data,
    get_project_search_engines,
    get_regions,
    remove_keyword_or_group_of_keywords,
    remove_search_system,
    search_project_in_user_projects,
    start_checking_keyword_groups,
    KeywordsAddingView,
    AddProjectView,
    KeywordEditingView,
    ProjectEditView,
    DetailProjectView,
    SearchSystemsAddingView,
    SearchSystemsEditingView,
)

app_name = 'project'
urlpatterns = [
    path('ajax/get_keywords_and_keyword_groups_of_project/', get_keywords_and_keyword_groups_of_project,
         name='get_keywords_and_keyword_groups_of_project'),
    path('ajax/get_project_search_engines/', get_project_search_engines,
         name='get_project_search_engines'),
    path('ajax/<slug:slug>/add_keywords_group/', add_keyword_group, name='add_group_of_keywords'),
    path('ajax/filter_project_data/', get_filtered_project_data, name='filter_project_data'),
    path('ajax/regions/', get_regions, name='get_regions'),
    path('ajax/remove_keyword_or_group_of_keywords/', remove_keyword_or_group_of_keywords,
         name='remove_keyword_or_group_of_keywords'),
    path('ajax/remove_search_system/', remove_search_system, name='remove_search_system'),
    path('ajax/start_checking_keyword_groups/', start_checking_keyword_groups,
         name='start_checking_keyword_groups'),
    path('ajax/search_project_in_user_projects/', search_project_in_user_projects,
         name='search_project_in_user_projects'),
    path('<slug:slug>/keywords/add/', KeywordsAddingView.as_view(), name='add_keywords'),
    path('<slug:slug>/search_system/add/', SearchSystemsAddingView.as_view(), name='add_search_system'),
    path('add/', AddProjectView.as_view(), name='project_create'),
    path('<slug:slug>/settings/keywords/edit/', KeywordEditingView.as_view(), name='edit_keywords'),
    path('<slug:slug>/settings/project/edit/', ProjectEditView.as_view(), name='edit_project'),
    path('<slug:slug>/settings/search_systems/edit/', SearchSystemsEditingView.as_view(), name='edit_search_systems'),
    path('<slug:slug>/', DetailProjectView.as_view(), name='project_details'),

]

templates/basic.html
{% load bootstrap5 static menu_where_user_projects_are_tags %}

<!DOCTYPE html>

<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Project{% endblock %}</title>
    {% bootstrap_css %}
    <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/assets/js/jquery-ui-1.12.1.custom/jquery-ui.min.css' %}">

</head>

<body class="d-flex flex-column m-0 p-0">

<header class="navbar navbar-expand-sm navbar-dark fs-5" style="background-color: #074691;">

    <nav class="container-fluid">
        <a class="navbar-brand ms-2" href="https://flexites.org/" target="_blank">
            <img id="logo-img" src="{% static 'img/logo.png' %}">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav w-100">
                <li class="nav-item me-5">
                    <a class="nav-link text-white" aria-current="page" href="/">Главная страница</a>
                </li>
                <li class="nav-item ms-5 me-3">
                    <a class="nav-link text-white" href="#">Отчеты</a>
                </li>
                <li class="nav-item ms-2 me-4">
                    <a class="nav-link text-white" href="#">Доступы</a>
                </li>
                <li class="nav-item flex-grow-1 me-2">
                    <a class="nav-link text-white" href="#">Другие ссылки</a>
                </li>

                {% if user.is_authenticated %}
                    <li class="nav-item dropdown me-3">
                        <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-expanded="false">
                            {{ user.email }}
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>
                                <a class="dropdown-item" href="{% url 'project:project_create' %}">Добавить проект</a>
                            </li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{% url 'account:logout' %}">Выйти</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li class="nav-item dropdown me-5 text-white">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown"
                           href="#" role="button" aria-haspopup="true"
                           aria-expanded="false">
                            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor"
                                 class="bi bi-person-x-fill" viewBox="0 0 16 16">
                                <path fill-rule="evenodd"
                                      d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm6.146-2.854a.5.5 0 0 1 .708 0L14 6.293l1.146-1.147a.5.5 0 0 1 .708.708L14.707 7l1.147 1.146a.5.5 0 0 1-.708.708L14 7.707l-1.146 1.147a.5.5 0 0 1-.708-.708L13.293 7l-1.147-1.146a.5.5 0 0 1 0-.708z"/>
                            </svg>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-sm-end" aria-labelledby="navbarDropdown">
                            <li>
                                <a class="dropdown-item" href="{% url 'account:login' %}">Вход</a>
                            </li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'account:register' %}">Регистрация</a>
                            </li>
                        </ul>
                    </li>
                {% endif %}
            </ul>
        </div>

    </nav>

</header>

<main class="d-flex flex-column h-100">
    <div class="d-flex flex-row align-items-lg-stretch flex-fill">
        <div class="col-2" style="background-color: #363636; color: #EEEEEE;">

            {% block sidebar %}
                {% if user.is_authenticated %}
                    {% get_user_projects %}
                {% endif %}
            {% endblock %}
        </div>

        <div class="col-10 h-100">
            {% bootstrap_messages %}
            {% block content %}
            {% endblock %}
        </div>

    </div>

</main>


{#{% bootstrap_javascript %}#}
<script src="{% static '/assets/js/jquery-ui-1.12.1.custom/external/jquery/jquery.js' %}"></script>
<script src="{% static '/assets/js/jquery-ui-1.12.1.custom/jquery-ui.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js"
        integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/"
        crossorigin="anonymous"></script>
<script type="module" src="{% static '/js/main.js' %}"></script>

</body>
</html>