config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='')),
    path('accounts/', include('account.urls', namespace='')),
    path('projects/', include('project.urls', namespace='')),
]

# Необходимо для работы debug_toolbar
if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls)), ] + urlpatterns

core/urls.py
from django.urls import path

from core.views import IndexView

app_name = 'core'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

project/urls.py
from django.urls import path

from project.views import (
    add_keyword_group,
    get_keywords_and_keyword_groups_of_project,
    get_filtered_project_data,
    get_project_search_engines,
    get_regions,
    remove_keyword_or_group_of_keywords,
    remove_search_system,
    search_project_in_user_projects,
    start_checking_keyword_groups,
    KeywordsAddingView,
    AddProjectView,
    KeywordEditingView,
    ProjectEditView,
    DetailProjectView,
    SearchSystemsAddingView,
    SearchSystemsEditingView,
)

app_name = 'project'
urlpatterns = [
    path('ajax/get_keywords_and_keyword_groups_of_project/', get_keywords_and_keyword_groups_of_project,
         name='get_keywords_and_keyword_groups_of_project'),
    path('ajax/get_project_search_engines/', get_project_search_engines,
         name='get_project_search_engines'),
    path('ajax/<slug:slug>/add_keywords_group/', add_keyword_group, name='add_group_of_keywords'),
    path('ajax/filter_project_data/', get_filtered_project_data, name='filter_project_data'),
    path('ajax/regions/', get_regions, name='get_regions'),
    path('ajax/remove_keyword_or_group_of_keywords/', remove_keyword_or_group_of_keywords,
         name='remove_keyword_or_group_of_keywords'),
    path('ajax/remove_search_system/', remove_search_system, name='remove_search_system'),
    path('ajax/start_checking_keyword_groups/', start_checking_keyword_groups,
         name='start_checking_keyword_groups'),
    path('ajax/search_project_in_user_projects/', search_project_in_user_projects,
         name='search_project_in_user_projects'),
    path('<slug:slug>/keywords/add/', KeywordsAddingView.as_view(), name='add_keywords'),
    path('<slug:slug>/search_system/add/', SearchSystemsAddingView.as_view(), name='add_search_system'),
    path('add/', AddProjectView.as_view(), name='project_create'),
    path('<slug:slug>/settings/keywords/edit/', KeywordEditingView.as_view(), name='edit_keywords'),
    path('<slug:slug>/settings/project/edit/', ProjectEditView.as_view(), name='edit_project'),
    path('<slug:slug>/settings/search_systems/edit/', SearchSystemsEditingView.as_view(), name='edit_search_systems'),
    path('<slug:slug>/', DetailProjectView.as_view(), name='project_details'),

]

project/models.py
from dateutil.relativedelta import relativedelta
from django.db import models
from django.urls import reverse
from django.utils.dateformat import DateFormat
from django.utils.text import slugify
from pydantic import BaseModel, validator, HttpUrl
from urllib.parse import urlparse

from account.models import CustomUser


def get_slug(url: str):
    parsed_url = urlparse(url)
    modified_domain = parsed_url.netloc.replace('.', '_')
    return slugify(modified_domain)


class Keywords(models.Model):
    name = models.TextField('Перечень слов', max_length=10000)
    keyword_groups = models.ForeignKey(
        'KeywordGroups',
        verbose_name='Группа ключевых слов',
        on_delete=models.CASCADE
    )

    class Meta:
        ordering = ('id',)
        verbose_name = 'Слово'
        verbose_name_plural = 'Слова'

    def __str__(self):
        return self.name

    def as_json(self, *args):
        return {field_name: getattr(self, field_name) for field_name in args}


class KeywordGroups(models.Model):
    name = models.CharField('Название группы', max_length=255)

    project = models.ForeignKey(
        'Project',
        verbose_name='Проект',
        on_delete=models.CASCADE
    )

    search_systems = models.ManyToManyField(
        'SearchSystem',
        blank=True
    )

    class Meta:
        ordering = ('id',)
        verbose_name = 'Группа ключевых слов'
        verbose_name_plural = 'Группы ключевых слов'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('project:keywords_group_detail', kwargs={'pk': self.id})

    def as_json(self, *args):
        keyword_groups_data = {}

        for field_name in args:
            if field_name == 'keywords':
                keywords_set = self.keywords_set.all()
                if keywords_set:
                    list_keywords = [keyword.as_json('id', 'name') for keyword in keywords_set]
                    keyword_groups_data['keywords'] = list_keywords
            else:
                keyword_groups_data[field_name] = getattr(self, field_name)

        return keyword_groups_data

    def keyword_group_search_system(self):
        return [search_system for search_system in self.search_systems.all()]

    keyword_group_search_system.short_description = 'Поисковые системы группы ключевых слов'


class PositionRequestPydantic(BaseModel):
    project_id: int
    domain: HttpUrl
    search_system_id: int
    keyword_group_id: int
    region_id: int
    query_keywords: str
    position: int = None
    url_site: HttpUrl = None


class Project(models.Model):
    LIMIT_HUNDRED = 100
    LIMIT_TWO_HUNDRED = 200

    LIMIT_CHOICES = (
        (LIMIT_HUNDRED, '100'),
        (LIMIT_TWO_HUNDRED, '200'),
    )

    DATE_CHOICES = (
        ('daily', 'Ежедневно'),
        ('every_three_days', 'Раз в 3 дня'),
        ('weekly', 'Раз в неделю'),
        ('monthly', 'Раз в месяц'),
        ('on_request', 'По запросу'),
    )

    name = models.CharField('Название проекта', max_length=255)
    slug = models.SlugField('Символьный код проекта', max_length=50, unique=True, db_index=True)
    domain = models.URLField(
        'Адрес сайта',
        max_length=50,
        unique=True,
        error_messages={
            'unique': 'Проект с таким адресом уже существует'
        }
    )

    limit_position = models.IntegerField(
        'Глубина сбора позиций',
        choices=LIMIT_CHOICES,
        default=LIMIT_HUNDRED,
        help_text='Сервис будет искать сайт включительно до 100-й или 200-й позиции'
    )

    start_check = models.CharField(
        'Периодичность проверок',
        max_length=30,
        choices=DATE_CHOICES,
        default='weekly',
    )

    created = models.DateTimeField('Дата добавления', auto_now_add=True)

    updated = models.DateTimeField('Дата изменения', auto_now=True)

    date_of_check = models.DateTimeField('Дата проверки', blank=True, null=True)

    date_of_next_check = models.DateTimeField('Дата следующей проверки', blank=True, null=True)

    author = models.ForeignKey(
        CustomUser,
        verbose_name='Автор проекта',
        on_delete=models.CASCADE
    )

    class Meta:
        ordering = ('-id',)
        verbose_name = 'Проект'
        verbose_name_plural = 'Проекты'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        # if not self.id:
        self.slug = get_slug(self.domain)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('project:project_details', kwargs={'slug': self.slug})

    def get_next_check_date(self, date_of_check):
        if self.start_check == 'daily':
            return date_of_check + relativedelta(days=1)

        elif self.start_check == 'every_three_days':
            return date_of_check + relativedelta(days=3)

        elif self.start_check == 'weekly':
            return date_of_check + relativedelta(weeks=1)

        elif self.start_check == 'monthly':
            return date_of_check + relativedelta(months=1)


class RankingsSite(models.Model):
    position = models.PositiveSmallIntegerField('Позиция сайта', )
    position_difference = models.SmallIntegerField('Разница позиций', null=True)
    project = models.ForeignKey(
        Project,
        verbose_name='Проект',
        on_delete=models.CASCADE
    )
    url_site = models.URLField('Адрес сайта', max_length=255)

    keywords = models.CharField('Ключевые слова', max_length=150)

    keyword_groups = models.ForeignKey(
        KeywordGroups,
        verbose_name='Группы ключевых слов',
        on_delete=models.CASCADE,
    )
    created = models.DateTimeField('Дата добавления', auto_now_add=True)
    updated = models.DateField('Дата изменения', auto_now=True)
    search_system = models.ForeignKey(
        'SearchSystem',
        verbose_name='Поисковая система',
        on_delete=models.CASCADE,
    )

    class Meta:
        ordering = ('-id',)
        verbose_name = 'Позиция сайта'
        verbose_name_plural = 'Позиции сайта'

    def as_json(self, *args):
        site_ranking = {}

        for field_name in args:
            if field_name == 'date_of_check':
                date_format = DateFormat(self.created)
                site_ranking['date_of_check'] = date_format.format('d.m.y')
            elif field_name == 'url_site':
                url_site = getattr(self, field_name)
                url_parsed = urlparse(url_site)
                site_ranking['url_site'] = url_parsed.path
            elif field_name == 'search_system':
                search_system = self.search_system.as_json('name', 'city')
                site_ranking['search_system'] = f'{search_system["name"]}, {search_system["city"]}'
            elif field_name == 'keyword_group':
                site_ranking['keyword_group'] = self.keyword_groups.as_json('name')
            elif field_name == 'keyword_groups':
                search_system_keyword_groups = self.search_system.keywordgroups_set.all()
                site_ranking['keyword_groups'] = [keyword_group.as_json('id', 'name') for keyword_group in
                                                  search_system_keyword_groups]
            else:
                site_ranking[field_name] = getattr(self, field_name)

        return site_ranking


class SearchEnginePydantic(BaseModel):
    name: str
    country: str
    city: str
    city_id: int
    language: str

    @validator('country', 'city')
    def field_value_is_a_string(cls, name):
        if name.isdigit():
            raise ValueError('Значение не должно быть только числом.')
        return name


class SearchSystem(models.Model):
    YANDEX = 'yandex'
    GOOGLE = 'google'
    ENGLISH = 'en'
    RUSSIAN = 'ru'

    LANGUAGE_CHOICES = (
        (ENGLISH, 'english'),
        (RUSSIAN, 'русский'),
    )

    SEARCH_SYSTEM_CHOICES = (
        (YANDEX, 'яндекс'),
        (GOOGLE, 'google'),
    )

    name = models.CharField(
        'Поисковая система',
        max_length=25,
        choices=SEARCH_SYSTEM_CHOICES,
        default=YANDEX
    )

    country = models.CharField('Страна', max_length=50)

    city = models.CharField('Регион', max_length=100)

    geo_id_city = models.IntegerField('Geo id города', )

    language = models.CharField(
        'Язык',
        max_length=25,
        choices=LANGUAGE_CHOICES,
        default=RUSSIAN
    )

    project = models.ForeignKey(
        Project,
        verbose_name='Проект',
        on_delete=models.CASCADE
    )

    class Meta:
        ordering = ('id',)
        verbose_name = 'Поисковая система'
        verbose_name_plural = 'Поисковые системы'

    def __str__(self):
        return f'{self.name}, {self.city}'

    def get_absolute_url(self):
        return reverse('project:search_system_detail', kwargs={'pk': self.pk})

    def as_json(self, *args):
        return {field_name: getattr(self, field_name) for field_name in args}

project/forms.py
from django import forms

from project.models import (
    Keywords,
    KeywordGroups,
    Project,
    SearchSystem
)


class FormAddingKeywordGroups(forms.ModelForm):
    name = forms.CharField(
        label='Название группы',
        max_length=255
    )

    class Meta:
        model = KeywordGroups
        fields = ('name',)


class KeywordsAddingForm(forms.ModelForm):
    name = forms.Textarea()

    class Meta:
        model = Keywords
        fields = ('name', 'keyword_groups')

    def __init__(self, *args, **kwargs):
        super(KeywordsAddingForm, self).__init__(*args, **kwargs)
        initial = kwargs.get('initial')
        self.fields['keyword_groups'].queryset = KeywordGroups.objects.filter(project__slug=initial['slug'])


class ProjectAddingForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ('name', 'domain', 'limit_position', 'start_check')


class ProjectEditingForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ('name', 'domain', 'limit_position', 'start_check')


class SearchSystemsAddingForm(forms.ModelForm):
    class Meta:
        model = SearchSystem
        fields = ('name', 'country', 'city', 'language')

templates/project/create.html
{% extends "basic.html" %}

{% load bootstrap5 %}

{% block title %}Добавление проекта{% endblock %}

{% block content %}

    <div class="container-fluid">

        <div class="d-flex flex-column align-items-center my-5 ">

            <div class="col-md-8 col-sm-12">
                <h3 class="text-center mb-3 p-2">Общая информация</h3>
                <p class="my-1 p-1">
                    Отслеживайте позиции вашего сайта в режиме реального времени во всех основных поисковых
                    системах.
                    Вы можете настроить параметры проекта и проверку позиций согласно вашим требованиям
                </p>
            </div>

            <form method="post" class="col-md-8 col-sm-12 mt-5">
                {% csrf_token %}

                <div class="mb-3 row">
                    <label class="col-md-3 col-form-label" for="id_name">Название проекта</label>
                    <div class="col-md-9">
                        <input type="text" name="name" maxlength="255" class="form-control"
                               placeholder="Название проекта" title="" required="required" id="id_name">
                    </div>
                </div>

                <div class="mb-3 row">
                    <label class="col-md-3 col-form-label" for="id_domain">Адрес сайта</label>
                    <div class="col-md-9">
                        <input type="url" name="domain" maxlength="50" class="form-control"
                               placeholder="Адрес сайта" title="" required="required" id="id_domain">
                    </div>
                </div>

                <div class="mb-3 row">
                    <label class="col-md-3 col-form-label" for="id_limit_position">Глубина сбора позиций</label>
                    <div class="col-md-9">
                        <select name="limit_position" class="form-select"
                                title="Сервис будет искать сайт включительно до 100-й или 200-й позиции"
                                id="id_limit_position">
                            <option value="100" selected="">100</option>
                            <option value="200">200</option>
                        </select>
                        <small class="form-text text-muted">
                            Сервис будет искать сайт включительно до 100-й или 200-й позиции
                        </small>
                    </div>
                </div>

                <div class="mb-3 row">
                    <label class="col-md-3 col-form-label" for="id_start_check">Периодичность проверок</label>
                    <div class="col-md-9">
                        <select name="start_check" class="form-select" title="" id="id_start_check">
                            <option value="daily">Ежедневно</option>
                            <option value="every_three_days">Раз в 3 дня</option>
                            <option value="weekly" selected="">Раз в неделю</option>
                            <option value="monthly">Раз в месяц</option>
                            <option value="on_request">По запросу</option>
                        </select></div>
                </div>

                <input type="hidden" name="next" value="{{ next }}">

                <div class="d-flex flex-row justify-content-between mt-5">
                    <div>
                        <a class="btn btn-outline-primary" type="button" href="{% url 'core:index' %}">Назад</a>
                    </div>
                    <button class="btn btn-outline-success" type="submit">Создать проект</button>
                </div>

            </form>

        </div>

    </div>

{% endblock %}

templates/project/edit.html
{% extends "basic.html" %}

{% load bootstrap5 menu_where_user_projects_are_tags %}

{% block title %}Настройки проекта{% endblock %}

{% block sidebar %}

    {% if user.is_authenticated %}
        {% get_project view.kwargs.slug %}
    {% endif %}

{% endblock %}


{% block content %}

    <div class="container-fluid">

        <div class="d-flex flex-column align-items-center my-5 ">

            <div class="col-md-8 col-sm-12">
                <h3 class="text-center mb-3 p-2">Общая информация</h3>
                <p class="my-1 p-1">
                    Отслеживайте позиции вашего сайта в режиме реального времени во всех основных поисковых
                    системах.
                    Вы можете настроить параметры проекта и проверку позиций согласно вашим требованиям
                </p>
            </div>

            <form method="post" class="col-md-8 col-sm-12 mt-5">
                {% csrf_token %}

                <div class="mb-3 row">
                    <label class="col-md-3 col-form-label" for="id_name">Название проекта</label>
                    <div class="col-md-9">
                        <input type="text" name="name" maxlength="255" class="form-control"
                               placeholder="Название проекта" title="" required="required" id="id_name">
                    </div>
                </div>

                <div class="mb-3 row">
                    <label class="col-md-3 col-form-label" for="id_domain">Адрес сайта</label>
                    <div class="col-md-9">
                        <input type="url" name="domain" maxlength="50" class="form-control"
                               placeholder="Адрес сайта" title="" required="required" id="id_domain">
                    </div>
                </div>

                <div class="mb-3 row">
                    <label class="col-md-3 col-form-label" for="id_limit_position">Глубина сбора позиций</label>
                    <div class="col-md-9">
                        <select name="limit_position" class="form-select"
                                title="Сервис будет искать сайт включительно до 100-й или 200-й позиции"
                                id="id_limit_position">
                            <option value="100" selected="">100</option>
                            <option value="200">200</option>
                        </select>
                        <small class="form-text text-muted">
                            Сервис будет искать сайт включительно до 100-й или 200-й позиции
                        </small>
                    </div>
                </div>

                <div class="mb-3 row">
                    <label class="col-md-3 col-form-label" for="id_start_check">Периодичность проверок</label>
                    <div class="col-md-9">
                        <select name="start_check" class="form-select" title="" id="id_start_check">
                            <option value="daily">Ежедневно</option>
                            <option value="every_three_days">Раз в 3 дня</option>
                            <option value="weekly" selected="">Раз в неделю</option>
                            <option value="monthly">Раз в месяц</option>
                            <option value="on_request">По запросу</option>
                        </select></div>
                </div>

                <input type="hidden" name="next" value="{{ next }}">

                <div class="mt-5">
                    <button class="btn btn-outline-success" type="submit">Применить</button>
                </div>

            </form>

            <div class="col-md-8 col-sm-12 mt-5">

                <div class="d-flex justify-content-between">
                    <a class="btn btn-outline-primary" type="button" href="{% url 'core:index' %}">Назад</a>
                    <a class="btn btn-outline-primary" href="{% url 'project:add_keywords' view.kwargs.slug %}"
                       type="button">Далее</a>
                </div>

            </div>

        </div>

    </div>

{% endblock %}